#cloud-config

hostname: dsi34
locale: fr_FR.UTF-8
timezone: Europe/Paris
manage_etc_hosts: true

users:
  - name: dsi34
    groups: [sudo, docker]
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL
    lock_passwd: false
    passwd: "$6$8c29N1zwuYzbmLIX$sc0O5YpbY2FZ2HJtPZr9Kxi6DRI8sV8XDt6Ha4jNjVJSscZSG4..qAK9OGqolQ2x6H1lTT2nDndIRLvd8Pz1"
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDu76k1GF9lNZT+2XFKWvCvT3XMIqzDfA4UeJE1aV+YY9Y61nG5wtCViVBWub62u8RyFWgKhA02TrHbPx2b132g1pUYjsa6SOI4wYhN+Uxw6wUQnC+V115BHHGQHnFMx9HxEzkI0TEysvZ5SEVt2AyZ/0Ib9ymbV0gVe2vbllhvT43MdptB+4H0HoWgcMtIkBvt66JYIuFOwnNzwZm1NjsqZHQiQwKAy7PDycCkMjKrSf1u3UBnStvhf9aD2H8Pq9mtGVlW3cFnTTI1pSp+TGH6L8FnT0UTpFecN2zwIuelPm+7UkX0pJNHy6nkoPYOinpDmwYYvnXME60vCOLivUjgYRXNY8VZhYpQ5K8AB6jCpi1Qcmks3EwHgJhQ2U1XPKyNio3cKPFOpf99119HVLoQbbGQw3KfG1XQTnkZFeEJqS6L4Lbupb8sSSQWF/Ubo6D7QgRRylS8CsfdYutBGd+jHfdhWu3aCVv86Gft/DHPcdqfNZoU9M8TH/Sdqb/VsnJ/w6Oaddx4HYrmGaVIH9ZeMLoIgqKGZVeL4K/cABZljcsMGR8aloCTU7iCmdFXmHSaH5jezPqK6EqPGRlKbZpf2iIdipaOA8g4NyXQzWyNixHBvN+5ghBJ03qqj/xaNh0xH9CbGEwvJ9G1oB+Dkfv3LMA5p7UHWofhLwMBRMdY9w== ton-email@example.com

ssh_pwauth: true

package_update: true
package_upgrade: true
packages:
  - ansible
  - git
  - net-tools
  - python3
  - python3-pip
  - unzip
  - curl
  - docker.io
  - docker-compose
  - ca-certificates
  - gnupg
  - lsb-release
  - nginx

runcmd:
  - systemctl enable nginx
  - systemctl start nginx
  # Terraform install
  - curl -fsSL https://releases.hashicorp.com/terraform/1.6.6/terraform_1.6.6_linux_amd64.zip -o /tmp/terraform.zip
  - unzip /tmp/terraform.zip -d /usr/local/bin/
  - rm /tmp/terraform.zip
  # Python packages
  - pip3 install boto3 pyvmomi
  # GitLab Runner
  - curl -L --output /usr/local/bin/gitlab-runner https://gitlab-runner-downloads.s3.amazonaws.com/latest/binaries/gitlab-runner-linux-amd64
  - chmod +x /usr/local/bin/gitlab-runner
  - useradd --comment 'GitLab Runner' --create-home gitlab-runner --shell /bin/bash || true
  - gitlab-runner install --user=gitlab-runner --working-directory=/home/gitlab-runner || true
  - gitlab-runner start || true
  # K3d + kubectl
  - bash -c "$(curl -s https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh)"
  - curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
  - install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
  # Reboot à la fin (facultatif, Azure reboot parfois à la création de VM)
  - reboot

write_files:
  - path: /etc/default/keyboard
    content: |
      XKBMODEL="pc105"
      XKBLAYOUT="fr"
      XKBVARIANT="azerty"
      XKBOPTIONS=""
    owner: root:root
    permissions: '0644'
