version: '3.8'
services:
  site:
    build: .
    container_name: devops-cyber-site
    ports:
      - "8080:80"
    volumes:
      - ./html:/usr/share/nginx/html    # montage du dossier html local
    restart: unless-stopped

  api:
    build: ./backend
    container_name: devops-cyber-api
    ports:
      - "5000:5000"
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: mariadb:latest
    container_name: devops-cyber-db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=supersecret
      - MYSQL_DATABASE=campagne
      - MYSQL_USER=devops
      - MYSQL_PASSWORD=devops123
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: